### ISSUE TITLE
There is no 1.0.3 CDN

### ISSUE THREAD

**Issue by deadcatssociety** [bvanderhoof/gist-embed#1]
I really love your code but 1.0.3 CDN is not exist.
I search from jsdelivr.net but only exist 1.0.2.

GET:
https://cdn.jsdelivr.net/npm/gist-embed@1.0.3/dist/gist-embed.min.js

RESP:
Couldn't find the requested release version 1.0.3.

update CDN please

**Comment by bvanderhoof** [comment]
Sorry about that - I had updated to 1.0.3 from my local source, but forgot to `npm publish`. It should work now, thanks for the heads up.
