### ISSUE TITLE
Wish: rest line show

### ISSUE THREAD

**Issue by deadcatssociety** [bvanderhoof/gist-embed#2]
sorry for my short-english

Wish: Show rest lines

ex: 
source code lines: 10 lines
option: data-gist-line="1, 3-5, 7-"
result: show 1, 3-5, 7-10 lines

data-gist-highlight-line option also

**Comment by bvanderhoof** [comment]
Sounds like a great idea. Feel free to contribute a patch and i will be
happy to include it. Directions are on the main page on how to develop a
new modifier. If not, will take a look within the next few days.

**Comment by deadcatssociety** [comment]
I know how to add that feature but  but I can't build develop environment (I totally noob to nodejs. I'm java/C# programmer)

1st try:
- VSCode + live server extension
-> tsc build fail
-> add lib[es2016]
-> export not found

2nd try:
- VSCode + live server extension
-> corejs install
-> require not found
-> now I know I need node.js server environment

3rd try:
- VSCode + nodejs + guide in your README.md
-> test.html is not found

I'm totally frustrated :(

**Comment by bvanderhoof** [comment]
Sorry for the trouble! I’ll take a look at your issues this week and see if
I can improve the documentation. Will also quickly implement the feature.
Thanks for looking into it.

**Comment by deadcatssociety** [comment]
thanks for your fasteeest reaction :D

**Comment by bvanderhoof** [comment]
Just added the support, check the example for how to use it (using your suggested syntax). I also updated the readme to make it less confusing when developing (I mistakenly referenced test.html instead of just going to localhost:8080 with no suffix path).
